- name: Install development environment
  hosts: localhost
  gather_facts: yes
  become: yes
  become_method: sudo
  ask_become_pass: yes
  vars_files:
      - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  vars:
    ansible_become_method: sudo
  roles:
    - geerlingguy.mac.homebrew
  tasks:
  - import_tasks: tasks/install_devenv.yml