---
# install_devenv.yml
- name: Add Homebrew to PATH
  shell: |
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
        eval "$(/opt/homebrew/bin/brew shellenv)"
- name: Initialize Git LFS
  shell: |
        git lfs install